/**
 * ---
 * purpose: Maintain a marker-delimited block in AGENTS.md that points agents at each registered tool, editing only inside CLIP's markers.
 * related:
 *   - ./skills.ts - The skill each pointer names when one exists.
 * ---
 */
import { existsSync, lstatSync, readFileSync, renameSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join, relative, resolve } from 'node:path';
import type { Registration } from './store.ts';

export const defaultAgentsFile = 'AGENTS.md';
const beginLine = '<!-- clip:begin generated by clip sync; edit registrations, not this block -->';
const endLine = '<!-- clip:end -->';
const heading = 'Installed CLI tools. Run them directly; read the usage source before a first call.';
const isBegin = (line: string) => line.startsWith('<!-- clip:begin');
const isEnd = (line: string) => line.startsWith('<!-- clip:end');

/** Where an agent gets usage detail for a tool: its skill file, or the tool's own help. */
export type UsageSource = (tool: Registration) => string | undefined;
export type AgentsMdPlan = { file: string; items: string[]; write: () => boolean };

const code = (value: string) => `\`${value}\``;
const shellWord = (value: string) => (/\s/.test(value) ? JSON.stringify(value) : value);

function pointer(tool: Registration, file: string, skillFile: string | undefined): string {
  const fromFile = skillFile && relative(dirname(file), skillFile);
  const usage = fromFile && !fromFile.startsWith('..') && !isAbsolute(fromFile) ? fromFile : (skillFile ?? `${shellWord(tool.executable)} --help`);
  /** Collapsing whitespace keeps a multi-line purpose from forging a marker line. */
  const purpose = tool.purpose.replace(/\s+/g, ' ').trim().replace(/\.?$/, '.');
  return `- ${code(tool.name)}: ${purpose} Usage: ${code(usage)}`;
}

/** Splits the file around CLIP's block, refusing anything but zero markers or exactly one begin before one end. */
function split(text: string, file: string): { before: string; after: string; found: boolean } {
  const lines = text.split('\n');
  const begins = lines.flatMap((line, index) => (isBegin(line) ? [index] : []));
  const ends = lines.flatMap((line, index) => (isEnd(line) ? [index] : []));
  if (!begins.length && !ends.length) return { before: text, after: '', found: false };
  const [begin, end] = [begins[0]!, ends[0]!];
  if (begins.length !== 1 || ends.length !== 1 || end < begin) throw new Error(`Refusing to edit a damaged CLIP block in ${file}. Restore one begin marker above one end marker, or delete both.`);
  return { before: lines.slice(0, begin).join('\n'), after: lines.slice(end + 1).join('\n'), found: true };
}

/** Validates the file and renders the block up front, so a refusal happens before any other sync target writes. */
export function planAgentsMd(tools: Registration[], path: string, usage: UsageSource): AgentsMdPlan {
  const file = resolve(path);
  if (isSymlink(file)) throw new Error(`Refusing to edit a symlinked agents file: ${file}`);
  const original = existsSync(file) ? readFileSync(file, 'utf8') : undefined;
  const { before, after, found } = split(original ?? '', file);
  const items = tools.map(tool => tool.name);
  return {
    file, items,
    write: () => {
      if (!tools.length && !found) return false;
      const block = tools.length ? [beginLine, heading, '', ...tools.map(tool => pointer(tool, file, usage(tool))), endLine].join('\n') : '';
      const parts = [before.trimEnd(), block, after.trim()].filter(Boolean);
      const next = parts.length ? `${parts.join('\n\n')}\n` : undefined;
      if (next === original) return false;
      if (next === undefined) unlinkSync(file);
      else replaceFile(file, next);
      return true;
    },
  };
}

/** lstat rather than existsSync, which follows links and so misses a dangling one that a write would follow. */
function isSymlink(path: string): boolean {
  try {
    return lstatSync(path).isSymbolicLink();
  } catch {
    return false;
  }
}

function replaceFile(file: string, content: string): void {
  const temp = join(dirname(file), `.${process.pid}.clip.tmp`);
  try {
    writeFileSync(temp, content);
    renameSync(temp, file);
  } finally {
    if (existsSync(temp)) unlinkSync(temp);
  }
}
