/**
 * ---
 * purpose: Maintain a marker-delimited block in AGENTS.md that points agents at each registered tool, editing only inside CLIP's markers.
 * related:
 *   - ./skills.ts - The skill each pointer names when one exists.
 * ---
 */
import { existsSync, lstatSync, readFileSync, renameSync, unlinkSync, writeFileSync } from 'node:fs';
import { basename, dirname, isAbsolute, join, relative, resolve } from 'node:path';
import type { Registration } from './store.ts';
import { agentTags, isShellCommand, type CommandEntry } from './commands-md.ts';

export const defaultAgentsFile = 'AGENTS.md';
const beginLine = '<!-- clip:begin generated by clip sync; edit registrations and the commands file, not this block -->';
const endLine = '<!-- clip:end -->';
const heading = 'Installed CLI tools. Run them directly; read the usage source before a first call.';
const tagMeanings: Record<string, string> = {
  safe: '`safe` runs without asking',
  writes: '`writes` edits tracked files, so expect a diff',
  destructive: "`destructive` can't be undone, so ask the user first",
  'long-running': '`long-running` never exits, so run it in the background',
  slow: '`slow` takes minutes',
  interactive: '`interactive` needs a person, so ask the user to run it',
  ci: '`ci` is what CI checks, so run it before calling work done',
};
const isBegin = (line: string) => line.startsWith('<!-- clip:begin');
const isEnd = (line: string) => line.startsWith('<!-- clip:end');

/** Where an agent gets usage detail for a tool: its skill file, or the tool's own help. */
export type UsageSource = (tool: Registration) => string | undefined;
export type AgentsMdPlan = { file: string; items: string[]; commands?: string[]; write: () => boolean };
export type ProjectCommands = { file: string; entries: CommandEntry[] };

const code = (value: string) => `\`${value}\``;
const shellWord = (value: string) => (/\s/.test(value) ? JSON.stringify(value) : value);
/** Collapsing whitespace keeps multi-line text from forging a marker line. */
const sentence = (text: string) => text.replace(/\s+/g, ' ').trim().replace(/\.?$/, '.');

/** A path relative to the agents file when it sits beneath it, otherwise as given. */
function fromAgentsFile(file: string, path: string): string | undefined {
  const fromFile = relative(dirname(file), path);
  return fromFile && !fromFile.startsWith('..') && !isAbsolute(fromFile) ? fromFile : undefined;
}

function pointer(tool: Registration, file: string, skillFile: string | undefined): string {
  const usage = (skillFile && fromAgentsFile(file, skillFile)) ?? skillFile ?? `${shellWord(basename(tool.executable))} --help`;
  return `- ${code(tool.name)}: ${sentence(tool.purpose)} Usage: ${code(usage)}`;
}

function commandLine(entry: CommandEntry): string {
  const tags = agentTags(entry);
  const label = entry.name === entry.command ? code(entry.command) : `${entry.name.replace(/\s+/g, ' ')}: ${code(entry.command)}`;
  return `- ${label}${tags.length ? ` [${tags.join(', ')}]` : ''}${entry.note ? ` — ${sentence(entry.note)}` : ''}`;
}

/** Shell commands only, once each: a layout repeating a menu command adds nothing for an agent. */
function agentCommands(entries: CommandEntry[]): CommandEntry[] {
  const seen = new Set<string>();
  return entries.filter(entry => isShellCommand(entry) && !seen.has(entry.command) && seen.add(entry.command));
}

function commandsSection(project: ProjectCommands, file: string, entries: CommandEntry[]): string[] {
  const used = new Set(entries.flatMap(agentTags));
  const legend = Object.keys(tagMeanings).filter(tag => used.has(tag)).map(tag => tagMeanings[tag]);
  const source = fromAgentsFile(file, project.file) ?? project.file;
  return [
    `Project commands from ${code(source)}. Run them from the project root.${legend.length ? ` Tags: ${legend.join('; ')}.` : ''}`,
    '', ...entries.map(commandLine),
  ];
}

/** Splits the file around CLIP's block, refusing anything but zero markers or exactly one begin before one end. */
function split(text: string, file: string): { before: string; after: string; found: boolean } {
  const lines = text.split('\n');
  const begins = lines.flatMap((line, index) => (isBegin(line) ? [index] : []));
  const ends = lines.flatMap((line, index) => (isEnd(line) ? [index] : []));
  if (!begins.length && !ends.length) return { before: text, after: '', found: false };
  const [begin, end] = [begins[0]!, ends[0]!];
  if (begins.length !== 1 || ends.length !== 1 || end < begin) throw new Error(`Refusing to edit a damaged CLIP block in ${file}. Restore one begin marker above one end marker, or delete both.`);
  return { before: lines.slice(0, begin).join('\n'), after: lines.slice(end + 1).join('\n'), found: true };
}

/** Validates the file and renders the block up front, so a refusal happens before any other sync target writes. */
export function planAgentsMd(tools: Registration[], path: string, usage: UsageSource, project?: ProjectCommands): AgentsMdPlan {
  const file = resolve(path);
  if (isSymlink(file)) throw new Error(`Refusing to edit a symlinked agents file: ${file}`);
  const original = existsSync(file) ? readFileSync(file, 'utf8') : undefined;
  const { before, after, found } = split(original ?? '', file);
  const items = tools.map(tool => tool.name);
  const commands = project && agentCommands(project.entries);
  return {
    file, items, ...(commands ? { commands: commands.map(entry => entry.name) } : {}),
    write: () => {
      const toolLines = tools.length ? [heading, '', ...tools.map(tool => pointer(tool, file, usage(tool)))] : [];
      const commandLines = project && commands?.length ? commandsSection(project, file, commands) : [];
      const content = [toolLines, commandLines].filter(lines => lines.length).flatMap((lines, index) => (index ? ['', ...lines] : lines));
      if (!content.length && !found) return false;
      const block = content.length ? [beginLine, ...content, endLine].join('\n') : '';
      const parts = [before.trimEnd(), block, after.trim()].filter(Boolean);
      const next = parts.length ? `${parts.join('\n\n')}\n` : undefined;
      if (next === original) return false;
      if (next === undefined) unlinkSync(file);
      else replaceFile(file, next);
      return true;
    },
  };
}

/** lstat rather than existsSync, which follows links and so misses a dangling one that a write would follow. */
function isSymlink(path: string): boolean {
  try {
    return lstatSync(path).isSymbolicLink();
  } catch {
    return false;
  }
}

function replaceFile(file: string, content: string): void {
  const temp = join(dirname(file), `.${process.pid}.clip.tmp`);
  try {
    writeFileSync(temp, content);
    renameSync(temp, file);
  } finally {
    if (existsSync(temp)) unlinkSync(temp);
  }
}
